# ══════════════════════════════════════════
# SecretStore — AWS에서 비밀을 가져오겠다
# IRSA로 인증 (키 없이!)
# [CHANGE] namespace, serviceAccountRef
# ══════════════════════════════════════════
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-store                      # [CHANGE] 이름
  namespace: student16                 # [CHANGE] 네임스페이스
spec:
  provider:
    aws:
      service: SecretsManager          # SecretsManager 또는 ParameterStore
      region: eu-west-3                # [CHANGE] 리전
      auth:
        jwt:
          serviceAccountRef:
            name: eso-notes            # [CHANGE] IRSA ServiceAccount
